### PR TITLE
Fixed a few typos

### PR DESCRIPTION
**Pull request by sfeeser**
I think VLAN range is a colon delimited -  name:x:y

### CODE REVIEW

**Comment by gyurco** [comment]
Hi! Thanks for this update, I'm not resistant to merge your patch, but can you please squash it to one or two commits? Like one commit for the typo fixes, another one to the youtube one. It's kinda messy to have one patch add something, then remove, then add again, then remove, and so on...

**Comment by gyurco** [comment]
Btw, it would be enough to add a link to the youtube video (good tutorial!), instead of embedding a flash movie (Flash is dead, at least for video playing).

**Comment by sfeeser** [comment]
Sorry, I was playing with the .rst file because I have exclusively used markdown up to now, so I sent you a trashed pull request with all my failed experiments before my wife told me to "put the computer down or else". So THANKS for NOT pulling it in!!!  First of all, let me say I like your code and I like your approach!  This is the cleanest ansible openstack deployment I have seen, and I was writing one before I found your project. When I saw the code, it looked so much like mine I figured it was crazy to duplicate the effort!  So, I will be installing an AIO, then modify it to satisfy a single controller, and six compute nodes.  I will be happy to send you clean  pull requests as I discover things.

**Comment by gyurco** [comment]
Great, hope you can find out how to use the installer (really tried to design it as simple as possible), I'll happily answer questions and review pull requests. There is always work to do, there are some components shipped in Ubuntu which are not covered, also the ones we're not using in production can be improved, too. And of course feel free to post pull requests to fix bugs/imperfections you found.
This patch looks good to me now, I'm pulling it.

**Pull request merged**
