### PR TITLE
Nova compute dependency fix

### PR DESCRIPTION
**Pull request by ahma**

### CODE REVIEW

**Comment by gyurco** [comment]
But what requires this? Openvswitch agent?
On a compute:
dpkg: dependency problems prevent removal of python-pymysql:
 python-keystone depends on python-pymysql.
 python-neutron depends on python-pymysql.
 python-tooz depends on python-pymysql.
 python-nova depends on python-pymysql.
So it was installed automatically.
Maybe python-neutron is the real missing dependency? Just want to understand why it worked until now.

**Comment by ahma** [comment]
**The problem:**
Ansible Output:
`TASK: [os_neutron | create neutron database] **********************************
failed: [sjc1-node107] => {"failed": true}
msg: the python mysqldb module is required
FATAL: all hosts have already failed -- aborting
PLAY RECAP ********************************************************************`

**Relevant code block** (_roles/os_neutron/tasks/main.yml_)
`- name: create neutron database
mysql_db: name={{ neutron_db }}
    login_host={{ neutron_mysql_server }} login_user=root login_password={{ mysql_root_password }}
    state=present
  run_once: True`

**Reason** (_mysql_db_):
[https://docs.ansible.com/ansible/mysql_db_module.html](url)
Requires the MySQLdb Python package on the remote host. For Ubuntu, this is as easy as apt-get install python-mysqldb. (See apt.) For CentOS/Fedora, this is as easy as yum install MySQL-python. (See yum.)

**Comment by gyurco** [comment]
Ah, that's a bug somewhere else: db operations should be run on the controller
Fixed here:
https://github.com/DoclerLabs/openstack/commit/618dc44ecd87b0438cbcef1cd2b30618a0dd6b88

**Comment by ahma** [comment]
Great thanks!

**Comment by gyurco** [comment]
Thanks for noticing the problem!

**Pull request closed without merging**
